create table monster_tb(
    pm_ID int not null auto_increment,
    pm_Name varchar(64) not null,
    pm_Level int not null,
    pm_Exp int not null,
    pm_Type int not null,
    pm_BS_Hp int not null,
    pm_BS_Atk int not null,
    pm_BS_Def int not null,
    pm_BS_Satk int not null,
    pm_BS_Sdef int not null,
    pm_BS_Spd int not null,
    pm_EV_Hp int not null,
    pm_EV_Atk int not null,
    pm_EV_Def int not null,
    pm_EV_Satk int not null,
    pm_EV_Sdef int not null,
    pm_EV_Spd int not null,
    pm_AtkLv int not null,
    pm_DefLv int not null,
    pm_SatkLv int not null,
    pm_SdefLv int not null,
    pm_SpdLv int not null,
    pm_AccLv int not null,
    pm_CritLv int not null,

    pm_Skill1 int not null,
    pm_Skill2 int not null,
    pm_Skill3 int not null, 
    pm_Skill4 int not null,

    pm_Ability int not null,
    primary key (id)
);
